name: size_estimation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: 14.8.1
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  ffi: ^2.1.4
  sensors_plus: ^7.0.0
  shared_preferences: ^2.5.4
  image_picker: ^1.1.2
  vector_math: ^2.1.4
  draggable_widget: ^2.0.0
  path_provider: ^2.1.5
  device_info_plus: ^10.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
